### ISSUE TITLE
question about dealii::DoFTools::make_hanging_node_constraints_from_serial

### ISSUE THREAD

**Issue by hppritcha** [dftfeDevelopers/dftfe#32]
HI All,

I'm helping some users with getting going with DFT FE version 1.0.2.  I'm noticing an issue with DEALII's DoFTtools, in particular DFT FE is using a ```make_hanging_node_constraints_from_serial``` method which is not defined in any of the branches of DEALII that are on the public github repo - git@github.com:dealii/dealii.git - that i've checked so far.

Does one need to use a special version of DEALII to build DFT FE 1.0.2?

Thanks,

Howard

**Comment by dsambit** [comment]
Hi Howard,

Thank you for your interest in DFT-FE. Actually we do need a customized version of dealii (https://github.com/dftfeDevelopers/dealii) as discussed in our [development version manual](https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2FdftfeDevelopers%2Fdftfe%2Fraw%2Fmanual%2Fmanual-develop.pdf&sa=D&sntz=1&usg=AOvVaw1vmBHuFTgT9rRBoSiytVfJ). For now we are recommending all users to use our development version (publicGithubDevelop branch in https://github.com/dftfeDevelopers/dftfe) which is GPU ported to both NVIDIA and AMD GPUs and also has some bug fixes and other capability improvements over the 1.0.2 version. Our next release for DFT-FE is slated to be in early July/August of this year.

Best,
Sambit

**Comment by hppritcha** [comment]
okay thanks for the pointers.  Do you anticipate the need for this special dealii branch long term or will changes in the dftfedevelopers version ultimately be integrated back into upstream dealii?

**Comment by dsambit** [comment]
We are working towards not requiring the customized dealii branch for pseudopotential only DFT calculations. This feature of being able to compile with the dealii release branch will be available in the upcoming release. We would still require the customized dealii branch for all-electron calculations.

**Comment by dsambit** [comment]
We are now able to compile with the dealii-9.5.2 release branch without requiring linking to a customized dealii branch. This feature is available in the `publicGithubDevelop` branch, soon to be 1.2 release.
